---
blank_issues_enabled: true

contact_links:
  - name: â“ Usage question - GitHub Discussions
    url: https://github.com/JP-Ellis/enphase-api/discussions
    about: >-
      Use GitHub Discussions for general usage questions, requiring a
      maintainer's answer. Make sure the question wasn't already asked.
