#:schema https://www.schemastore.org/any.json
[profile.ci]
# In CI, we want to run all tests instead of failing fast
fail-fast = false

# Some tests are flaky in CI
retries = { backoff = "exponential", count = 10, delay = "30s", jitter = true }

# Test is slow if it takes longer than 10 seconds and then terminated if 6x10
# seconds elapse
slow-timeout = { period = "10s", terminate-after = 6 }
